apiVersion: v1
kind: Service
metadata:
  name: stock-svc
  namespace: eshop
spec:
  selector:
    app: stock
  type: ClusterIP
  ports:
    - name: stock-svc-http-port
      port: 8080
      targetPort: 8080

