apiVersion: v1
kind: Service
metadata:
  name: relation-svc
  namespace: community
spec:
  selector:
    app: relation
  type: ClusterIP
  ports:
    - name: relation-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: relation-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

