apiVersion: v1
kind: Service
metadata:
  name: comment-svc
  namespace: eshop
spec:
  selector:
    app: comment
  type: ClusterIP
  ports:
    - name: comment-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: comment-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

