apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: eshop
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - name: order-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: order-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

