apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: community
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: user-svc-http-port
      port: 8080
      targetPort: 8080

