apiVersion: v1
kind: Service
metadata:
  name: community-svc
  namespace: community
spec:
  selector:
    app: community
  type: ClusterIP
  ports:
    - name: community-svc-http-port
      port: 8080
      targetPort: 8080

