apiVersion: v1
kind: Service
metadata:
  name: store-svc
  namespace: appliance-store
spec:
  selector:
    app: store
  type: ClusterIP
  ports:
    - name: store-svc-http-port
      port: 8080
      targetPort: 8080

