// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type AfterSalesLogicer interface {
	Create(ctx context.Context, req *CreateAfterSalesRequest) (*CreateAfterSalesReply, error)
	DeleteByID(ctx context.Context, req *DeleteAfterSalesByIDRequest) (*DeleteAfterSalesByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateAfterSalesByIDRequest) (*UpdateAfterSalesByIDReply, error)
	GetByID(ctx context.Context, req *GetAfterSalesByIDRequest) (*GetAfterSalesByIDReply, error)
	List(ctx context.Context, req *ListAfterSalesRequest) (*ListAfterSalesReply, error)
	CreateServiceOrderWithAssignment(ctx context.Context, req *CreateServiceOrderWithAssignmentRequest) (*CreateServiceOrderWithAssignmentReply, error)
}

type AfterSalesOption func(*afterSalesOptions)

type afterSalesOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *afterSalesOptions) apply(opts ...AfterSalesOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithAfterSalesHTTPResponse() AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.isFromRPC = false
	}
}

func WithAfterSalesRPCResponse() AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.isFromRPC = true
	}
}

func WithAfterSalesResponser(responser errcode.Responser) AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.responser = responser
	}
}

func WithAfterSalesLogger(zapLog *zap.Logger) AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.zapLog = zapLog
	}
}

func WithAfterSalesErrorToHTTPCode(e ...*errcode.Error) AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.httpErrors = e
	}
}

func WithAfterSalesRPCStatusToHTTPCode(s ...*errcode.RPCStatus) AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.rpcStatus = s
	}
}

func WithAfterSalesWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) AfterSalesOption {
	return func(o *afterSalesOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterAfterSalesRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic AfterSalesLogicer,
	opts ...AfterSalesOption) {

	o := &afterSalesOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &afterSalesRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type afterSalesRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                AfterSalesLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *afterSalesRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/afterSales", r.withMiddleware("POST", "/api/v1/afterSales", r.Create_2)...)
	r.iRouter.Handle("DELETE", "/api/v1/afterSales/:id", r.withMiddleware("DELETE", "/api/v1/afterSales/:id", r.DeleteByID_2)...)
	r.iRouter.Handle("PUT", "/api/v1/afterSales/:id", r.withMiddleware("PUT", "/api/v1/afterSales/:id", r.UpdateByID_2)...)
	r.iRouter.Handle("GET", "/api/v1/afterSales/:id", r.withMiddleware("GET", "/api/v1/afterSales/:id", r.GetByID_2)...)
	r.iRouter.Handle("POST", "/api/v1/afterSales/list", r.withMiddleware("POST", "/api/v1/afterSales/list", r.List_2)...)
	r.iRouter.Handle("POST", "/api/v1/afterSales/service-orders", r.withMiddleware("POST", "/api/v1/afterSales/service-orders", r.CreateServiceOrderWithAssignment_0)...)

}

func (r *afterSalesRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *afterSalesRouter) Create_2(c *gin.Context) {
	req := &CreateAfterSalesRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *afterSalesRouter) DeleteByID_2(c *gin.Context) {
	req := &DeleteAfterSalesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *afterSalesRouter) UpdateByID_2(c *gin.Context) {
	req := &UpdateAfterSalesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *afterSalesRouter) GetByID_2(c *gin.Context) {
	req := &GetAfterSalesByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *afterSalesRouter) List_2(c *gin.Context) {
	req := &ListAfterSalesRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *afterSalesRouter) CreateServiceOrderWithAssignment_0(c *gin.Context) {
	req := &CreateServiceOrderWithAssignmentRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.CreateServiceOrderWithAssignment(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
