// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type AuditLogLogicer interface {
	Create(ctx context.Context, req *CreateAuditLogRequest) (*CreateAuditLogReply, error)
	DeleteByID(ctx context.Context, req *DeleteAuditLogByIDRequest) (*DeleteAuditLogByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateAuditLogByIDRequest) (*UpdateAuditLogByIDReply, error)
	GetByID(ctx context.Context, req *GetAuditLogByIDRequest) (*GetAuditLogByIDReply, error)
	List(ctx context.Context, req *ListAuditLogRequest) (*ListAuditLogReply, error)
}

type AuditLogOption func(*auditLogOptions)

type auditLogOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *auditLogOptions) apply(opts ...AuditLogOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithAuditLogHTTPResponse() AuditLogOption {
	return func(o *auditLogOptions) {
		o.isFromRPC = false
	}
}

func WithAuditLogRPCResponse() AuditLogOption {
	return func(o *auditLogOptions) {
		o.isFromRPC = true
	}
}

func WithAuditLogResponser(responser errcode.Responser) AuditLogOption {
	return func(o *auditLogOptions) {
		o.responser = responser
	}
}

func WithAuditLogLogger(zapLog *zap.Logger) AuditLogOption {
	return func(o *auditLogOptions) {
		o.zapLog = zapLog
	}
}

func WithAuditLogErrorToHTTPCode(e ...*errcode.Error) AuditLogOption {
	return func(o *auditLogOptions) {
		o.httpErrors = e
	}
}

func WithAuditLogRPCStatusToHTTPCode(s ...*errcode.RPCStatus) AuditLogOption {
	return func(o *auditLogOptions) {
		o.rpcStatus = s
	}
}

func WithAuditLogWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) AuditLogOption {
	return func(o *auditLogOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterAuditLogRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic AuditLogLogicer,
	opts ...AuditLogOption) {

	o := &auditLogOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &auditLogRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type auditLogRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                AuditLogLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *auditLogRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/auditLog", r.withMiddleware("POST", "/api/v1/auditLog", r.Create_4)...)
	r.iRouter.Handle("DELETE", "/api/v1/auditLog/:id", r.withMiddleware("DELETE", "/api/v1/auditLog/:id", r.DeleteByID_4)...)
	r.iRouter.Handle("PUT", "/api/v1/auditLog/:id", r.withMiddleware("PUT", "/api/v1/auditLog/:id", r.UpdateByID_4)...)
	r.iRouter.Handle("GET", "/api/v1/auditLog/:id", r.withMiddleware("GET", "/api/v1/auditLog/:id", r.GetByID_4)...)
	r.iRouter.Handle("POST", "/api/v1/auditLog/list", r.withMiddleware("POST", "/api/v1/auditLog/list", r.List_4)...)

}

func (r *auditLogRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *auditLogRouter) Create_4(c *gin.Context) {
	req := &CreateAuditLogRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *auditLogRouter) DeleteByID_4(c *gin.Context) {
	req := &DeleteAuditLogByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *auditLogRouter) UpdateByID_4(c *gin.Context) {
	req := &UpdateAuditLogByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *auditLogRouter) GetByID_4(c *gin.Context) {
	req := &GetAuditLogByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *auditLogRouter) List_4(c *gin.Context) {
	req := &ListAuditLogRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
