// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type CheckDetailLogicer interface {
	Create(ctx context.Context, req *CreateCheckDetailRequest) (*CreateCheckDetailReply, error)
	DeleteByCheckID(ctx context.Context, req *DeleteCheckDetailByCheckIDRequest) (*DeleteCheckDetailByCheckIDReply, error)
	UpdateByCheckID(ctx context.Context, req *UpdateCheckDetailByCheckIDRequest) (*UpdateCheckDetailByCheckIDReply, error)
	GetByCheckID(ctx context.Context, req *GetCheckDetailByCheckIDRequest) (*GetCheckDetailByCheckIDReply, error)
	List(ctx context.Context, req *ListCheckDetailRequest) (*ListCheckDetailReply, error)
}

type CheckDetailOption func(*checkDetailOptions)

type checkDetailOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *checkDetailOptions) apply(opts ...CheckDetailOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithCheckDetailHTTPResponse() CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.isFromRPC = false
	}
}

func WithCheckDetailRPCResponse() CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.isFromRPC = true
	}
}

func WithCheckDetailResponser(responser errcode.Responser) CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.responser = responser
	}
}

func WithCheckDetailLogger(zapLog *zap.Logger) CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.zapLog = zapLog
	}
}

func WithCheckDetailErrorToHTTPCode(e ...*errcode.Error) CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.httpErrors = e
	}
}

func WithCheckDetailRPCStatusToHTTPCode(s ...*errcode.RPCStatus) CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.rpcStatus = s
	}
}

func WithCheckDetailWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) CheckDetailOption {
	return func(o *checkDetailOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterCheckDetailRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic CheckDetailLogicer,
	opts ...CheckDetailOption) {

	o := &checkDetailOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &checkDetailRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type checkDetailRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                CheckDetailLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *checkDetailRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/checkDetail", r.withMiddleware("POST", "/api/v1/checkDetail", r.Create_6)...)
	r.iRouter.Handle("DELETE", "/api/v1/checkDetail/:checkID", r.withMiddleware("DELETE", "/api/v1/checkDetail/:checkID", r.DeleteByCheckID_0)...)
	r.iRouter.Handle("PUT", "/api/v1/checkDetail/:checkID", r.withMiddleware("PUT", "/api/v1/checkDetail/:checkID", r.UpdateByCheckID_0)...)
	r.iRouter.Handle("GET", "/api/v1/checkDetail/:checkID", r.withMiddleware("GET", "/api/v1/checkDetail/:checkID", r.GetByCheckID_0)...)
	r.iRouter.Handle("POST", "/api/v1/checkDetail/list", r.withMiddleware("POST", "/api/v1/checkDetail/list", r.List_6)...)

}

func (r *checkDetailRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *checkDetailRouter) Create_6(c *gin.Context) {
	req := &CreateCheckDetailRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *checkDetailRouter) DeleteByCheckID_0(c *gin.Context) {
	req := &DeleteCheckDetailByCheckIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByCheckID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *checkDetailRouter) UpdateByCheckID_0(c *gin.Context) {
	req := &UpdateCheckDetailByCheckIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByCheckID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *checkDetailRouter) GetByCheckID_0(c *gin.Context) {
	req := &GetCheckDetailByCheckIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByCheckID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *checkDetailRouter) List_6(c *gin.Context) {
	req := &ListCheckDetailRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
