// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type InventoryLogicer interface {
	Create(ctx context.Context, req *CreateInventoryRequest) (*CreateInventoryReply, error)
	DeleteByID(ctx context.Context, req *DeleteInventoryByIDRequest) (*DeleteInventoryByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateInventoryByIDRequest) (*UpdateInventoryByIDReply, error)
	GetByID(ctx context.Context, req *GetInventoryByIDRequest) (*GetInventoryByIDReply, error)
	List(ctx context.Context, req *ListInventoryRequest) (*ListInventoryReply, error)
	ExecuteTransfer(ctx context.Context, req *ExecuteTransferRequest) (*ExecuteTransferReply, error)
}

type InventoryOption func(*inventoryOptions)

type inventoryOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *inventoryOptions) apply(opts ...InventoryOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithInventoryHTTPResponse() InventoryOption {
	return func(o *inventoryOptions) {
		o.isFromRPC = false
	}
}

func WithInventoryRPCResponse() InventoryOption {
	return func(o *inventoryOptions) {
		o.isFromRPC = true
	}
}

func WithInventoryResponser(responser errcode.Responser) InventoryOption {
	return func(o *inventoryOptions) {
		o.responser = responser
	}
}

func WithInventoryLogger(zapLog *zap.Logger) InventoryOption {
	return func(o *inventoryOptions) {
		o.zapLog = zapLog
	}
}

func WithInventoryErrorToHTTPCode(e ...*errcode.Error) InventoryOption {
	return func(o *inventoryOptions) {
		o.httpErrors = e
	}
}

func WithInventoryRPCStatusToHTTPCode(s ...*errcode.RPCStatus) InventoryOption {
	return func(o *inventoryOptions) {
		o.rpcStatus = s
	}
}

func WithInventoryWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) InventoryOption {
	return func(o *inventoryOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterInventoryRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic InventoryLogicer,
	opts ...InventoryOption) {

	o := &inventoryOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &inventoryRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type inventoryRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                InventoryLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *inventoryRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/inventory", r.withMiddleware("POST", "/api/v1/inventory", r.Create_18)...)
	r.iRouter.Handle("DELETE", "/api/v1/inventory/:id", r.withMiddleware("DELETE", "/api/v1/inventory/:id", r.DeleteByID_16)...)
	r.iRouter.Handle("PUT", "/api/v1/inventory/:id", r.withMiddleware("PUT", "/api/v1/inventory/:id", r.UpdateByID_16)...)
	r.iRouter.Handle("GET", "/api/v1/inventory/:id", r.withMiddleware("GET", "/api/v1/inventory/:id", r.GetByID_16)...)
	r.iRouter.Handle("POST", "/api/v1/inventory/list", r.withMiddleware("POST", "/api/v1/inventory/list", r.List_18)...)
	r.iRouter.Handle("POST", "/api/v1/inventory/transfer", r.withMiddleware("POST", "/api/v1/inventory/transfer", r.ExecuteTransfer_0)...)

}

func (r *inventoryRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *inventoryRouter) Create_18(c *gin.Context) {
	req := &CreateInventoryRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *inventoryRouter) DeleteByID_16(c *gin.Context) {
	req := &DeleteInventoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *inventoryRouter) UpdateByID_16(c *gin.Context) {
	req := &UpdateInventoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *inventoryRouter) GetByID_16(c *gin.Context) {
	req := &GetInventoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *inventoryRouter) List_18(c *gin.Context) {
	req := &ListInventoryRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *inventoryRouter) ExecuteTransfer_0(c *gin.Context) {
	req := &ExecuteTransferRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.ExecuteTransfer(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
