// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type ProductSkuLogicer interface {
	Create(ctx context.Context, req *CreateProductSkuRequest) (*CreateProductSkuReply, error)
	DeleteByID(ctx context.Context, req *DeleteProductSkuByIDRequest) (*DeleteProductSkuByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateProductSkuByIDRequest) (*UpdateProductSkuByIDReply, error)
	GetByID(ctx context.Context, req *GetProductSkuByIDRequest) (*GetProductSkuByIDReply, error)
	List(ctx context.Context, req *ListProductSkuRequest) (*ListProductSkuReply, error)
}

type ProductSkuOption func(*productSkuOptions)

type productSkuOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *productSkuOptions) apply(opts ...ProductSkuOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithProductSkuHTTPResponse() ProductSkuOption {
	return func(o *productSkuOptions) {
		o.isFromRPC = false
	}
}

func WithProductSkuRPCResponse() ProductSkuOption {
	return func(o *productSkuOptions) {
		o.isFromRPC = true
	}
}

func WithProductSkuResponser(responser errcode.Responser) ProductSkuOption {
	return func(o *productSkuOptions) {
		o.responser = responser
	}
}

func WithProductSkuLogger(zapLog *zap.Logger) ProductSkuOption {
	return func(o *productSkuOptions) {
		o.zapLog = zapLog
	}
}

func WithProductSkuErrorToHTTPCode(e ...*errcode.Error) ProductSkuOption {
	return func(o *productSkuOptions) {
		o.httpErrors = e
	}
}

func WithProductSkuRPCStatusToHTTPCode(s ...*errcode.RPCStatus) ProductSkuOption {
	return func(o *productSkuOptions) {
		o.rpcStatus = s
	}
}

func WithProductSkuWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) ProductSkuOption {
	return func(o *productSkuOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterProductSkuRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic ProductSkuLogicer,
	opts ...ProductSkuOption) {

	o := &productSkuOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &productSkuRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type productSkuRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                ProductSkuLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *productSkuRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/productSku", r.withMiddleware("POST", "/api/v1/productSku", r.Create_32)...)
	r.iRouter.Handle("DELETE", "/api/v1/productSku/:id", r.withMiddleware("DELETE", "/api/v1/productSku/:id", r.DeleteByID_30)...)
	r.iRouter.Handle("PUT", "/api/v1/productSku/:id", r.withMiddleware("PUT", "/api/v1/productSku/:id", r.UpdateByID_30)...)
	r.iRouter.Handle("GET", "/api/v1/productSku/:id", r.withMiddleware("GET", "/api/v1/productSku/:id", r.GetByID_30)...)
	r.iRouter.Handle("POST", "/api/v1/productSku/list", r.withMiddleware("POST", "/api/v1/productSku/list", r.List_32)...)

}

func (r *productSkuRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *productSkuRouter) Create_32(c *gin.Context) {
	req := &CreateProductSkuRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productSkuRouter) DeleteByID_30(c *gin.Context) {
	req := &DeleteProductSkuByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productSkuRouter) UpdateByID_30(c *gin.Context) {
	req := &UpdateProductSkuByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productSkuRouter) GetByID_30(c *gin.Context) {
	req := &GetProductSkuByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productSkuRouter) List_32(c *gin.Context) {
	req := &ListProductSkuRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
