// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type ProductCategoryLogicer interface {
	Create(ctx context.Context, req *CreateProductCategoryRequest) (*CreateProductCategoryReply, error)
	DeleteByID(ctx context.Context, req *DeleteProductCategoryByIDRequest) (*DeleteProductCategoryByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateProductCategoryByIDRequest) (*UpdateProductCategoryByIDReply, error)
	GetByID(ctx context.Context, req *GetProductCategoryByIDRequest) (*GetProductCategoryByIDReply, error)
	List(ctx context.Context, req *ListProductCategoryRequest) (*ListProductCategoryReply, error)
}

type ProductCategoryOption func(*productCategoryOptions)

type productCategoryOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *productCategoryOptions) apply(opts ...ProductCategoryOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithProductCategoryHTTPResponse() ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.isFromRPC = false
	}
}

func WithProductCategoryRPCResponse() ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.isFromRPC = true
	}
}

func WithProductCategoryResponser(responser errcode.Responser) ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.responser = responser
	}
}

func WithProductCategoryLogger(zapLog *zap.Logger) ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.zapLog = zapLog
	}
}

func WithProductCategoryErrorToHTTPCode(e ...*errcode.Error) ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.httpErrors = e
	}
}

func WithProductCategoryRPCStatusToHTTPCode(s ...*errcode.RPCStatus) ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.rpcStatus = s
	}
}

func WithProductCategoryWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) ProductCategoryOption {
	return func(o *productCategoryOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterProductCategoryRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic ProductCategoryLogicer,
	opts ...ProductCategoryOption) {

	o := &productCategoryOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &productCategoryRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type productCategoryRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                ProductCategoryLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *productCategoryRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/productCategory", r.withMiddleware("POST", "/api/v1/productCategory", r.Create_28)...)
	r.iRouter.Handle("DELETE", "/api/v1/productCategory/:id", r.withMiddleware("DELETE", "/api/v1/productCategory/:id", r.DeleteByID_26)...)
	r.iRouter.Handle("PUT", "/api/v1/productCategory/:id", r.withMiddleware("PUT", "/api/v1/productCategory/:id", r.UpdateByID_26)...)
	r.iRouter.Handle("GET", "/api/v1/productCategory/:id", r.withMiddleware("GET", "/api/v1/productCategory/:id", r.GetByID_26)...)
	r.iRouter.Handle("POST", "/api/v1/productCategory/list", r.withMiddleware("POST", "/api/v1/productCategory/list", r.List_28)...)

}

func (r *productCategoryRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *productCategoryRouter) Create_28(c *gin.Context) {
	req := &CreateProductCategoryRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productCategoryRouter) DeleteByID_26(c *gin.Context) {
	req := &DeleteProductCategoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productCategoryRouter) UpdateByID_26(c *gin.Context) {
	req := &UpdateProductCategoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productCategoryRouter) GetByID_26(c *gin.Context) {
	req := &GetProductCategoryByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productCategoryRouter) List_28(c *gin.Context) {
	req := &ListProductCategoryRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
