// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type ProductMediaLogicer interface {
	Create(ctx context.Context, req *CreateProductMediaRequest) (*CreateProductMediaReply, error)
	DeleteByID(ctx context.Context, req *DeleteProductMediaByIDRequest) (*DeleteProductMediaByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateProductMediaByIDRequest) (*UpdateProductMediaByIDReply, error)
	GetByID(ctx context.Context, req *GetProductMediaByIDRequest) (*GetProductMediaByIDReply, error)
	List(ctx context.Context, req *ListProductMediaRequest) (*ListProductMediaReply, error)
}

type ProductMediaOption func(*productMediaOptions)

type productMediaOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *productMediaOptions) apply(opts ...ProductMediaOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithProductMediaHTTPResponse() ProductMediaOption {
	return func(o *productMediaOptions) {
		o.isFromRPC = false
	}
}

func WithProductMediaRPCResponse() ProductMediaOption {
	return func(o *productMediaOptions) {
		o.isFromRPC = true
	}
}

func WithProductMediaResponser(responser errcode.Responser) ProductMediaOption {
	return func(o *productMediaOptions) {
		o.responser = responser
	}
}

func WithProductMediaLogger(zapLog *zap.Logger) ProductMediaOption {
	return func(o *productMediaOptions) {
		o.zapLog = zapLog
	}
}

func WithProductMediaErrorToHTTPCode(e ...*errcode.Error) ProductMediaOption {
	return func(o *productMediaOptions) {
		o.httpErrors = e
	}
}

func WithProductMediaRPCStatusToHTTPCode(s ...*errcode.RPCStatus) ProductMediaOption {
	return func(o *productMediaOptions) {
		o.rpcStatus = s
	}
}

func WithProductMediaWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) ProductMediaOption {
	return func(o *productMediaOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterProductMediaRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic ProductMediaLogicer,
	opts ...ProductMediaOption) {

	o := &productMediaOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &productMediaRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type productMediaRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                ProductMediaLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *productMediaRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/productMedia", r.withMiddleware("POST", "/api/v1/productMedia", r.Create_30)...)
	r.iRouter.Handle("DELETE", "/api/v1/productMedia/:id", r.withMiddleware("DELETE", "/api/v1/productMedia/:id", r.DeleteByID_28)...)
	r.iRouter.Handle("PUT", "/api/v1/productMedia/:id", r.withMiddleware("PUT", "/api/v1/productMedia/:id", r.UpdateByID_28)...)
	r.iRouter.Handle("GET", "/api/v1/productMedia/:id", r.withMiddleware("GET", "/api/v1/productMedia/:id", r.GetByID_28)...)
	r.iRouter.Handle("POST", "/api/v1/productMedia/list", r.withMiddleware("POST", "/api/v1/productMedia/list", r.List_30)...)

}

func (r *productMediaRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *productMediaRouter) Create_30(c *gin.Context) {
	req := &CreateProductMediaRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productMediaRouter) DeleteByID_28(c *gin.Context) {
	req := &DeleteProductMediaByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productMediaRouter) UpdateByID_28(c *gin.Context) {
	req := &UpdateProductMediaByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productMediaRouter) GetByID_28(c *gin.Context) {
	req := &GetProductMediaByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *productMediaRouter) List_30(c *gin.Context) {
	req := &ListProductMediaRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
