// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type SalesOrderItemLogicer interface {
	Create(ctx context.Context, req *CreateSalesOrderItemRequest) (*CreateSalesOrderItemReply, error)
	DeleteByID(ctx context.Context, req *DeleteSalesOrderItemByIDRequest) (*DeleteSalesOrderItemByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateSalesOrderItemByIDRequest) (*UpdateSalesOrderItemByIDReply, error)
	GetByID(ctx context.Context, req *GetSalesOrderItemByIDRequest) (*GetSalesOrderItemByIDReply, error)
	List(ctx context.Context, req *ListSalesOrderItemRequest) (*ListSalesOrderItemReply, error)
}

type SalesOrderItemOption func(*salesOrderItemOptions)

type salesOrderItemOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *salesOrderItemOptions) apply(opts ...SalesOrderItemOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithSalesOrderItemHTTPResponse() SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.isFromRPC = false
	}
}

func WithSalesOrderItemRPCResponse() SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.isFromRPC = true
	}
}

func WithSalesOrderItemResponser(responser errcode.Responser) SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.responser = responser
	}
}

func WithSalesOrderItemLogger(zapLog *zap.Logger) SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.zapLog = zapLog
	}
}

func WithSalesOrderItemErrorToHTTPCode(e ...*errcode.Error) SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.httpErrors = e
	}
}

func WithSalesOrderItemRPCStatusToHTTPCode(s ...*errcode.RPCStatus) SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.rpcStatus = s
	}
}

func WithSalesOrderItemWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) SalesOrderItemOption {
	return func(o *salesOrderItemOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterSalesOrderItemRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic SalesOrderItemLogicer,
	opts ...SalesOrderItemOption) {

	o := &salesOrderItemOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &salesOrderItemRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type salesOrderItemRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                SalesOrderItemLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *salesOrderItemRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/salesOrderItem", r.withMiddleware("POST", "/api/v1/salesOrderItem", r.Create_42)...)
	r.iRouter.Handle("DELETE", "/api/v1/salesOrderItem/:id", r.withMiddleware("DELETE", "/api/v1/salesOrderItem/:id", r.DeleteByID_40)...)
	r.iRouter.Handle("PUT", "/api/v1/salesOrderItem/:id", r.withMiddleware("PUT", "/api/v1/salesOrderItem/:id", r.UpdateByID_40)...)
	r.iRouter.Handle("GET", "/api/v1/salesOrderItem/:id", r.withMiddleware("GET", "/api/v1/salesOrderItem/:id", r.GetByID_40)...)
	r.iRouter.Handle("POST", "/api/v1/salesOrderItem/list", r.withMiddleware("POST", "/api/v1/salesOrderItem/list", r.List_42)...)

}

func (r *salesOrderItemRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *salesOrderItemRouter) Create_42(c *gin.Context) {
	req := &CreateSalesOrderItemRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderItemRouter) DeleteByID_40(c *gin.Context) {
	req := &DeleteSalesOrderItemByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderItemRouter) UpdateByID_40(c *gin.Context) {
	req := &UpdateSalesOrderItemByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderItemRouter) GetByID_40(c *gin.Context) {
	req := &GetSalesOrderItemByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderItemRouter) List_42(c *gin.Context) {
	req := &ListSalesOrderItemRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
