// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/go-dev-frame/sponge/pkg/errcode"
	"github.com/go-dev-frame/sponge/pkg/gin/middleware"
)

type SalesOrderLogicer interface {
	Create(ctx context.Context, req *CreateSalesOrderRequest) (*CreateSalesOrderReply, error)
	DeleteByID(ctx context.Context, req *DeleteSalesOrderByIDRequest) (*DeleteSalesOrderByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateSalesOrderByIDRequest) (*UpdateSalesOrderByIDReply, error)
	GetByID(ctx context.Context, req *GetSalesOrderByIDRequest) (*GetSalesOrderByIDReply, error)
	List(ctx context.Context, req *ListSalesOrderRequest) (*ListSalesOrderReply, error)
	GenerateHotSalesReport(ctx context.Context, req *GenerateHotSalesReportRequest) (*GenerateHotSalesReportReply, error)
}

type SalesOrderOption func(*salesOrderOptions)

type salesOrderOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *salesOrderOptions) apply(opts ...SalesOrderOption) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithSalesOrderHTTPResponse() SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.isFromRPC = false
	}
}

func WithSalesOrderRPCResponse() SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.isFromRPC = true
	}
}

func WithSalesOrderResponser(responser errcode.Responser) SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.responser = responser
	}
}

func WithSalesOrderLogger(zapLog *zap.Logger) SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.zapLog = zapLog
	}
}

func WithSalesOrderErrorToHTTPCode(e ...*errcode.Error) SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.httpErrors = e
	}
}

func WithSalesOrderRPCStatusToHTTPCode(s ...*errcode.RPCStatus) SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.rpcStatus = s
	}
}

func WithSalesOrderWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) SalesOrderOption {
	return func(o *salesOrderOptions) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func RegisterSalesOrderRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic SalesOrderLogicer,
	opts ...SalesOrderOption) {

	o := &salesOrderOptions{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isFromRPC, o.httpErrors, o.rpcStatus)
	}
	if o.zapLog == nil {
		o.zapLog, _ = zap.NewProduction()
	}

	r := &salesOrderRouter{
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		zapLog:                o.zapLog,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type salesOrderRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                SalesOrderLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *salesOrderRouter) register() {
	r.iRouter.Handle("POST", "/api/v1/salesOrder", r.withMiddleware("POST", "/api/v1/salesOrder", r.Create_40)...)
	r.iRouter.Handle("DELETE", "/api/v1/salesOrder/:id", r.withMiddleware("DELETE", "/api/v1/salesOrder/:id", r.DeleteByID_38)...)
	r.iRouter.Handle("PUT", "/api/v1/salesOrder/:id", r.withMiddleware("PUT", "/api/v1/salesOrder/:id", r.UpdateByID_38)...)
	r.iRouter.Handle("GET", "/api/v1/salesOrder/:id", r.withMiddleware("GET", "/api/v1/salesOrder/:id", r.GetByID_38)...)
	r.iRouter.Handle("POST", "/api/v1/salesOrder/list", r.withMiddleware("POST", "/api/v1/salesOrder/list", r.List_40)...)
	r.iRouter.Handle("GET", "/api/v1/salesOrder/hot-sales", r.withMiddleware("GET", "/api/v1/salesOrder/hot-sales", r.GenerateHotSalesReport_0)...)

}

func (r *salesOrderRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

func (r *salesOrderRouter) Create_40(c *gin.Context) {
	req := &CreateSalesOrderRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.Create(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderRouter) DeleteByID_38(c *gin.Context) {
	req := &DeleteSalesOrderByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.DeleteByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderRouter) UpdateByID_38(c *gin.Context) {
	req := &UpdateSalesOrderByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.UpdateByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderRouter) GetByID_38(c *gin.Context) {
	req := &GetSalesOrderByIDRequest{}
	var err error

	if err = c.ShouldBindUri(req); err != nil {
		r.zapLog.Warn("ShouldBindUri error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GetByID(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderRouter) List_40(c *gin.Context) {
	req := &ListSalesOrderRequest{}
	var err error

	if err = c.ShouldBindJSON(req); err != nil {
		r.zapLog.Warn("ShouldBindJSON error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.List(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}

func (r *salesOrderRouter) GenerateHotSalesReport_0(c *gin.Context) {
	req := &GenerateHotSalesReportRequest{}
	var err error

	if err = c.ShouldBindQuery(req); err != nil {
		r.zapLog.Warn("ShouldBindQuery error", zap.Error(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}

	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	out, err := r.iLogic.GenerateHotSalesReport(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

	r.iResponse.Success(c, out)
}
