apiVersion: v1
kind: Service
metadata:
  name: edusys-gw-svc
  namespace: edusys
spec:
  selector:
    app: edusys-gw
  type: ClusterIP
  ports:
    - name: edusys-gw-svc-http-port
      port: 8080
      targetPort: 8080

