apiVersion: v1
kind: Service
metadata:
  name: eshop-gw-svc
  namespace: eshop
spec:
  selector:
    app: eshop-gw
  type: ClusterIP
  ports:
    - name: eshop-gw-svc-http-port
      port: 8080
      targetPort: 8080

