apiVersion: v1
kind: Service
metadata:
  name: flash-sale-svc
  namespace: eshop
spec:
  selector:
    app: flash-sale
  type: ClusterIP
  ports:
    - name: flash-sale-svc-http-port
      port: 8080
      targetPort: 8080

