apiVersion: v1
kind: Service
metadata:
  name: creation-svc
  namespace: community
spec:
  selector:
    app: creation
  type: ClusterIP
  ports:
    - name: creation-svc-http-port
      port: 8080
      targetPort: 8080

