apiVersion: apps/v1
kind: Deployment
metadata:
  name: creation-dm
  namespace: community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creation
  template:
    metadata:
      name: creation-pod
      labels:
        app: creation
    spec:
      containers:
        - name: creation
          image: /community/creation:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./creation", "-c", "/app/configs/creation.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: creation-vl
              mountPath: /app/configs/
              readOnly: true

          ports:
            - name: grpc-port
              containerPort: 8282
            - name: metrics-port
              containerPort: 8283
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8282"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8282"]

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: creation-vl
          configMap:
            name: creation-config
