apiVersion: v1
kind: Service
metadata:
  name: creation-svc
  namespace: community
spec:
  selector:
    app: creation
  type: ClusterIP
  ports:
    - name: creation-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: creation-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

